### create member - v1
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
  "name": "kwon"
}

### create member - v2
POST http://localhost:8080/api/v2/members
Content-Type: application/json

{
  "name": "kwon"
}

### update member
PUT http://localhost:8080/api/v2/members/3
Content-Type: application/json

{
  "name": "kwon modify"
}

### query member - v1
GET http://localhost:8080/api/v1/members/

### query member - v2
GET http://localhost:8080/api/v2/members/